[package]
authors = ["Shohei Jinno <shohei.jinno@gmail.com>"]
edition = "2018"
name = "puppy-notifier"
version = "0.1.0"

[dependencies]
dotenv = "0.15"
reqwest = {version = "0.11.0", features = ["blocking"]}
scraper = "0.12"
